myapp/urls.py
from django.urls import path
from myapp import views



urlpatterns = [
    path('home/', views.index, name='home'),
    path('add-employee', views.add_employee, name='add_employee'),
    path('details/<int:pk>', views.details, name='details'),
    path('update/<int:pk>', views.update, name='update'),
    path('management/', views.management, name='management'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('register/', views.register, name='register'),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]   

myapp/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    DESIGNATION_CHOICES = [
        ('Manager', 'Manager'),
        ('Developer', 'Developer'),
        ('Designer', 'Designer'),
        ('Analyst', 'Analyst'),
        ('Intern', 'Intern'),
    ]
    name = models.CharField(max_length=100)
    address = models.TextField()
    phone_number = models.CharField(max_length=15, unique=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    designation = models.CharField(max_length=50, choices=DESIGNATION_CHOICES)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

myapp/forms.py
from typing import Any
from django import forms
from django.contrib.auth import authenticate
from .models import Employee
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name', 'address', 'phone_number', 'salary', 'designation', 'description']
        
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-input mt-1 block w-full h-12 pl-4 pr-4 rounded-lg border border-gray-300',  
                'placeholder': 'Enter full name',
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-input mt-1 block w-full h-12 pl-4 pr-4 rounded-lg border border-gray-300',  
                'placeholder': 'Enter address',
            }),
            'phone_number': forms.TextInput(attrs={
                'class': 'form-input mt-1 block w-full h-12 pl-4 pr-4 rounded-lg border border-gray-300',  
                'placeholder': 'Enter phone number',
            }),
            'salary': forms.NumberInput(attrs={
                'class': 'form-input mt-1 block w-full h-12 pl-4 pr-4 rounded-lg border border-gray-300',
                'placeholder': '$ Enter salary',
            }),
            'designation': forms.Select(attrs={
                'class': 'border-gray-300 rounded-md p-2 w-full',
            }),

            'description': forms.Textarea(attrs={
                'class': 'form-input mt-1 block w-full h-12 pl-4 pr-4 rounded-lg border border-gray-300',
                'placeholder': 'Enter a brief profile summary',
                'rows': 1,
            }),
        }

    def __init__(self, *args, **kwargs):
        is_update = kwargs.pop('is_update', False)
        super(EmployeeForm, self).__init__(*args, **kwargs)

        if is_update:
            self.fields['salary'].widget.attrs['readonly'] = True
            self.fields['designation'].disabled = True

    def clean_designation(self):
        return self.initial['designation']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-base py-2 px-3',
                'placeholder': 'Enter your username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-base py-2 px-3',
                'placeholder': 'Enter your email'
            }),
        
        }


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg py-2 px-3',
        'placeholder': 'Enter your username',
        'autofocus': True
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg py-2 px-3',
        'placeholder': 'Enter your password',
    }))




class CustomUserChangeForm(UserChangeForm):
    old_password = forms.CharField(
        label='Old Password',
        widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Enter old password'}),
        required=False
    )
    new_password1 = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Enter new password'}),
        required=False
    )
    new_password2 = forms.CharField(
        label='Confirm New Password',
        widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': 'Confirm new password'}),
        required=False
    )


    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')

        if old_password or new_password1 or new_password2:
            if not old_password:
                self.add_error('old_password', 'This field is required.')
            else:
                user = authenticate(username=self.instance.username, password=old_password)
                if not user:
                    self.add_error('old_password', 'Incorrect password.')

            if new_password1 and new_password2:
                if new_password1 != new_password2:
                    self.add_error('new_password2', 'Passwords do not match.')
            
            else:
                self.add_error('new_password1', 'This field is required.')

        return cleaned_data
                

    def save(self, commit=True):
        user = super().save(commit=False)
        new_password1 = self.cleaned_data.get('new_password1')

        if new_password1:
            user.set_password(new_password1)
        if commit:
            user.save()
        return user

myapp/views.py
from django.shortcuts import render, redirect
from . forms import EmployeeForm, CustomUserCreationForm, CustomAuthenticationForm, CustomUserChangeForm
from django.http import HttpResponse
from .models import Employee
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash

# Create your views here.



################### Index for home
@login_required
def index(request):
    employees = Employee.objects.all()
    return render(request, 'home.html', {'employees': employees})


################### Add Employee
@login_required
def add_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return HttpResponse(form.errors, status=400)
    else:
        form = EmployeeForm()
        return render(request, 'add_employee.html', {'form': form})
    

################### Details
@login_required
def details(request, pk):
    employee = Employee.objects.get(pk=pk)
    return render(request, 'details.html', {'employee': employee})


################### management
@login_required
def management(request):
    employees = Employee.objects.all()
    return render(request, 'management.html', {'employees': employees})


################### update
@login_required
def update(request, pk):
    employee = Employee.objects.get(pk=pk)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee, is_update=True)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return HttpResponse(form.errors, status=400)
    else:
        form = EmployeeForm(instance=employee, is_update=True)
        return render(request, 'update.html', {'form': form})



################## delete
@login_required
def delete(request, pk):
    employee = Employee.objects.get(pk=pk)
    employee.delete()
    return redirect('management')
    

################## Register
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registration successful! You are now logged in.')
            return redirect('home')
        else:
            messages.error(request, 'Invalid data! Please check the form.')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})


################## Login
def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=user_name, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Invalid username or password')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'login.html', {'form': form})


################## login 
@login_required
def logout_view(request):
    logout(request)
    return redirect('login')



################## Profile 
@login_required
def profile(request):
    user = request.user 
    return render(request, 'profile.html', {'user': user})



################## edit_profile
@login_required
def edit_profile(request):
    user = request.user  # Get the current logged-in user
    
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        
        if form.is_valid():
            user = form.save()  # Save the form and update the user instance
            # If password is updated, update the session so the user doesn't get logged out
            update_session_auth_hash(request, user)
            return redirect('profile')  # Redirect to the profile page or any other page
        else:
            return HttpResponse(form.errors, status=400)
    
    else:
        form = CustomUserChangeForm(instance=user)  # Prepopulate the form with the current user data
    
    return render(request, 'edit_profile.html', {'form': form})

    

myapp/templates/add_employee.html
{% extends "common/base.html" %}

{% block content %}
    <div class="container mx-auto mt-8">
        <div class="max-w-lg mx-auto bg-gray-200 shadow-lg rounded-lg px-8 py-6">
            <h2 class="text-3xl font-bold mb-6 text-center">Add New Employee</h2>
            
            <form method="POST">
                {% csrf_token %}
                
                <div class="mb-4">
                    <label for="id_name" class="block text-gray-700 font-bold mb-2">Name</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                        <p class="text-red-500 text-sm">{{ form.name.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_address" class="block text-gray-700 font-bold mb-2">Address</label>
                    {{ form.address }}
                    {% if form.address.errors %}
                        <p class="text-red-500 text-sm">{{ form.address.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_phone_number" class="block text-gray-700 font-bold mb-2">Phone Number</label>
                    {{ form.phone_number }}
                    {% if form.phone_number.errors %}
                        <p class="text-red-500 text-sm">{{ form.phone_number.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_salary" class="block text-gray-700 font-bold mb-2">Salary</label>
                    {{ form.salary }}
                    {% if form.salary.errors %}
                        <p class="text-red-500 text-sm">{{ form.salary.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_designation" class="block text-gray-700 font-bold mb-2">Designation</label>
                    {{ form.designation }}
                    {% if form.designation.errors %}
                        <p class="text-red-500 text-sm">{{ form.designation.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_description" class="block text-gray-700 font-bold mb-2 center">Description</label>
                    {{ form.description }}
                    {% if form.description.errors %}
                        <p class="text-red-500 text-sm">{{ form.description.errors }}</p>
                    {% endif %}
                </div>

                <div class="mt-6">
                    <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">
                        Create
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/details.html
{% extends "common/base.html" %}

{% block content %}

<h2 class="text-2xl font-bold mb-4 text-center">Employee Details</h2>

<div class="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-6">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Name</h3>
            <p class="text-gray-700">{{ employee.name }}</p>
        </div>
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Contact</h3>
            <p class="text-gray-700">{{ employee.phone_number }}</p>
        </div>
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Designation</h3>
            <p class="text-gray-700">{{ employee.designation }}</p>
        </div>
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Salary</h3>
            <p class="text-gray-700">${{ employee.salary }}</p>
        </div>
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Address</h3>
            <p class="text-gray-700">{{ employee.address }}</p>
        </div>
        <div class="p-4 border-b border-gray-200">
            <h3 class="text-lg font-semibold mb-2 text-gray-800">Description</h3>
            <p class="text-gray-700">{{ employee.description }}</p>
        </div>
    </div>
</div>

{% endblock %}

myapp/templates/edit_profile.html
{% extends "common/base.html" %}

{% load custom_filter %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="w-full max-w-lg bg-white p-8 rounded-lg shadow-md">
        <h2 class="text-2xl font-bold text-gray-800 text-center mb-6">Update Profile</h2>
        
        <form method="POST">
            {% csrf_token %}

            <!-- Email Field -->
            <div class="mb-6">
                <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
                {{ form.email|add_class:"form-input mt-1 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500"}}
                {% if form.email.errors %}
                    <p class="text-red-500 text-sm">{{ form.email.errors }}</p>
                {% endif %}
            </div>

            <!-- Old Password Field -->
            <div class="mb-6">
                <label for="old_password" class="block text-sm font-medium text-gray-700">Old Password</label>
                {{ form.old_password|add_class:"form-input mt-1 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500" }}
                {% if form.old_password.errors %}
                    <p class="text-red-500 text-sm">{{ form.old_password.errors }}</p>
                {% endif %}
            </div>

            <!-- New Password Field -->
            <div class="mb-6">
                <label for="new_password1" class="block text-sm font-medium text-gray-700">New Password</label>
                {{ form.new_password1|add_class:"form-input mt-1 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500" }}
                {% if form.new_password1.errors %}
                    <p class="text-red-500 text-sm">{{ form.new_password1.errors }}</p>
                {% endif %}
            </div>

            <!-- Confirm New Password Field -->
            <div class="mb-6">
                <label for="new_password2" class="block text-sm font-medium text-gray-700">Confirm New Password</label>
                {{ form.new_password2|add_class:"form-input mt-1 block w-full px-4 py-2 border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500" }}
                {% if form.new_password2.errors %}
                    <p class="text-red-500 text-sm">{{ form.new_password2.errors }}</p>
                {% endif %}
            </div>

            <!-- Submit Button -->
            <div class="flex items-center justify-between">
                <button type="submit" class="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out focus:outline-none">
                    Update Profile
                </button>
            </div>

        </form>
    </div>
</div>
{% endblock %}

myapp/templates/home.html
{% extends "common/base.html" %}

{% block content %}
    <h2 class="text-2xl font-bold mb-4 text-center">Employee List</h2>
    <table class="table-auto w-full mt-4 border-collapse border border-gray-200">
        <thead>
            <tr class="bg-gray-100">
                <th class="border px-4 py-2">Name</th>
                <th class="border px-4 py-2">Designation</th>
                <th class="border px-4 py-2">Description</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            
            <tr>
                <td class="border px-4 py-2 text-blue-800"><a href="{% url 'details' employee.pk %}">{{ employee.name }}</a></td>     
                <td class="border px-4 py-2">{{ employee.designation }}</td>
                <td class="border px-4 py-2">{{ employee.description }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center py-4">No employees found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

myapp/templates/login.html
{% extends "common/base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="max-w-md w-full bg-white shadow-lg rounded-lg p-8">
        <div class="flex justify-center mb-6">
            <img src="https://i.ibb.co/yqXx61r/pngtree-library-logo-vector-icon-illustration-art-front-concept-vector-png-image-39896862.png" alt="Logo" class="h-50px w-auto">
        </div>
        <h2 class="text-center text-2xl font-bold text-gray-700 mb-6">Login</h2>
        {% if messages %}
            {% for message in messages %}
                <p class="text-red-500 text-sm text-center">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <form method="POST" class="space-y-6">
            {% csrf_token %}
            <div>
                <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
                {{ form.username }}
                {% if form.username.errors %}
                    <p class="text-red-500 text-sm">{{ form.username.errors }}</p>
                {% endif %}
            </div>

            <div>
                <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                {{ form.password }}
                {% if form.password.errors %}
                    <p class="text-red-500 text-sm">{{ form.password.errors }}</p>
                {% endif %}
            </div>
            
            <div class="flex items-center justify-between">
                <button type="submit" class="w-full bg-indigo-600 text-white font-semibold py-2 px-4 rounded hover:bg-indigo-500 focus:outline-none">
                    Login
                </button>
            </div>
            <p class="text-center text-sm text-gray-700">Don't have an account? <a href="{% url 'register' %}" class="text-indigo-600 font-semibold">Register</a></p>
        </form>
    </div>
</div>
{% endblock content %}

myapp/templates/management.html
{% extends "common/base.html" %}

{% block content %}
    <h2 class="text-2xl font-bold mb-4 text-center">Manage Employee</h2>
    <table class="table-auto w-full mt-4 border-collapse border border-gray-200">
        <thead>
            <tr class="bg-gray-100">
                <th class="border px-3 py-2">Name</th>
                <th class="border px-7 py-2">Designation</th>
                <th class="border px-2 py-2 w-60">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
            <tr>
                <td class="border text-center px-3 py-3 text-blue-800"><a href="{% url 'details' employee.pk %}">{{ employee.name }}</a></td>     
                <td class="border text-center px-7 py-3">{{ employee.designation }}</td>
                <td class="border text-center px-2 py-3 w-60">
                    <div>
                        <a href="{% url 'update' employee.pk %}" class="bg-yellow-500 text-white px-5 py-2 rounded">Edit</a>
                        <a href="{% url 'delete' employee.pk %}" class="bg-red-500 text-white px-5 py-2 rounded">Delete</a>
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6" class="text-center py-4">No employees found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

myapp/templates/profile.html
{% extends "common/base.html" %}

{% block content %}
<div class="flex justify-center items-center mt-5 ">
    <div class="max-w-lg w-full bg-gray-200 shadow-md rounded-lg p-8">
        <h2 class="text-center text-2xl font-bold text-gray-700 mb-6">Your Profile</h2>
        <div class="space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-700">Username</label>
                <div class="text-lg font-semibold text-gray-900">
                    {{ user.username }}
                </div>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700">Email</label>
                <div class="text-lg font-semibold text-gray-900">
                    {{ user.email }}
                </div>
            </div>
        </div>
        <div class="mt-6 space-y-4">
            <a href="{% url 'edit_profile' %}" class="w-full block bg-indigo-600 text-white font-semibold py-2 px-4 rounded hover:bg-indigo-500 text-center">
                Edit Profile
            </a>
        </div>
    </div>
</div>
{% endblock content %}

myapp/templates/register.html
{% extends "common/base.html" %}

{% block content %}

<div class="flex justify-center items-center min-h-screen bg-gray-100">
    <div class="max-w-md w-full bg-white shadow-md rounded-lg p-8">
        
        <h2 class="text-center text-2xl font-bold text-gray-700 mb-6">Register</h2>
        
    <form method="POST" class="space-y-6">
    {% csrf_token %}
    
    <div>
        <label for="username" class="block text-sm font-medium text-gray-700">Username</label>
        {{ form.username }}
        {% if form.username.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.username.errors }}</p>
        {% endif %}
    </div>
    
    <div>
        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
        {{ form.email }}
        {% if form.email.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.email.errors }}</p>
        {% endif %}
    </div>

    <div class="pass1">
        <label for="password1" class="block text-sm font-medium text-gray-700">Password</label>
        <input type="password" name="password1" id="password1" class="form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-base py-2 px-3" placeholder="Enter your password">
        {% if form.password1.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.password1.errors }}</p>
        {% endif %}
    </div>

    <div class="pass2">
        <label for="password2" class="block text-sm font-medium text-gray-700">Confirm Password</label>
        <input type="password" name="password2" id="password2" class="form-input mt-2 block w-full bg-white border border-gray-300 rounded-lg shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-base py-2 px-3" placeholder="Confirm your password">
        {% if form.password2.errors %}
            <p class="text-red-500 text-sm mt-2">{{ form.password2.errors }}</p>
        {% endif %}
    </div>
    
    <div class="flex items-center justify-between">
        <button type="submit" class="w-full bg-indigo-600 text-white font-semibold py-2 px-4 rounded hover:bg-indigo-500 focus:outline-none">
            Register
        </button>
    </div>

    <div>
        <p>Already have an account? <a href="{% url 'login' %}" class="text-indigo-600 font-semibold">Login</a></p>
    </div>
</form>

    </div>
</div>
    
{% endblock content %}

myapp/templates/update.html
{% extends "common/base.html" %}

{% block content %}
    <div class="container mx-auto mt-8">
        <div class="max-w-lg mx-auto bg-white shadow-lg rounded-lg px-8 py-6">
            <h2 class="text-3xl font-bold mb-6 text-center">Edit Employee</h2>
            
            <form method="POST">
                {% csrf_token %}
                
                <div class="mb-4">
                    <label for="id_name" class="block text-gray-700 font-bold mb-2">Name</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                        <p class="text-red-500 text-sm">{{ form.name.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_address" class="block text-gray-700 font-bold mb-2">Address</label>
                    {{ form.address }}
                    {% if form.address.errors %}
                        <p class="text-red-500 text-sm">{{ form.address.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_phone_number" class="block text-gray-700 font-bold mb-2">Phone Number</label>
                    {{ form.phone_number }}
                    {% if form.phone_number.errors %}
                        <p class="text-red-500 text-sm">{{ form.phone_number.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_salary" class="block text-gray-700 font-bold mb-2">Salary</label>
                    {{ form.salary }}
                    {% if form.salary.errors %}
                        <p class="text-red-500 text-sm">${{ form.salary.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_designation" class="block text-gray-700 font-bold mb-2">Designation</label>
                    {{ form.designation }}
                    {% if form.designation.errors %}
                        <p class="text-red-500 text-sm">{{ form.designation.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="id_description" class="block text-gray-700 font-bold mb-2 center">Description</label>
                    {{ form.description }}
                    {% if form.description.errors %}
                        <p class="text-red-500 text-sm">{{ form.description.errors }}</p>
                    {% endif %}
                </div>
                
                <div class="mt-6">
                    <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">
                        Update
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}